name: Uptime
description: "A simple sit/stand timer app for Android and iOS called Uptime."
publish_to: 'none'
version: 0.1.0-alpha.1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.5.0
  flutter_timezone: 4.1.1
  timezone: ^0.10.0
  permission_handler: ^11.3.1
  android_intent_plus: ^5.3.0
  wakelock_plus: ^1.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash:

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  windows:
    generate: true
    icon_size: 48
  image_path: "assets/logo.png"


flutter_native_splash:
  color: "#ffffff" # Set your background color
  image: assets/splash.png # Path to your splash image
  android: true
  ios: true
